sudo: required
services:
  - docker

before_install:
  - docker build -t cimedia/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run cimedia/react-test npm test -- --coverage

after_success:
  - docker build -t cimedia/multi-client ./client
  - docker build -t cimedia/multi-nginx ./nginx
  - docker build -t cimedia/multi-server ./server
  - docker build -t cimedia/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push those images to docker hub
  - docker pushcimedia/multi-client
  - docker pushcimedia/multi-nginx
  - docker pushcimedia/multi-server
  - docker pushcimedia/multi-worker
