language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t cimedia/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cimedia/react-test npm test

after_success:
  - docker build -t cimedia/multi-client ./client
  - docker build -t cimedia/multi-nginx ./nginx
  - docker build -t cimedia/multi-server ./server
  - docker build -t cimedia/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push those images to docker hub
  - docker push cimedia/multi-client
  - docker push cimedia/multi-nginx
  - docker push cimedia/multi-server
  - docker push cimedia/multi-worker
